Rg/warm start option
exanauts/BlockNLPModels.jl pull request #8
Opened 2022-05-18 20:14 UTC by grishabh147

This PR adds an option to warm-start the `FullSpaceModel` with initial primal and dual solution guesses.

2022-05-18 21:04 UTC, frapac requested changes
Nice! I only have a few minor comments. 

The main question is what do we do with `get_hessian`? I think we can use the same function both for `AugmentedNLPBlockModel` and for `ProxAugmentedNLPBlockModel`. But I would suggest addressing this in a future PR.

2022-05-18 21:04 UTC, frapac commented on src/full_space.jl
> +- `x0::Union{Vector{Float64}, Nothing}`: warm start primal solution
Maybe specify that by default `x0` is a vector of zeroes?

2022-05-18 21:04 UTC, frapac commented on src/full_space.jl
> +        x0::Union{Vector{Float64}, Nothing} = nothing,
how about using directly?
```julia
x0 = NLPModels.get_x0(m)
```
and implements the corresponding `NLPModels.get_x0` function for the different `AbstractBlockNLPModel`?

2022-05-18 21:04 UTC, frapac commented on src/prox_augmented_block.jl
> +    P::AbstractArray # proximal term penalty parameters
do we assume that the proximal parameter is a vector (so a diagonal matrix) by default?

2022-05-18 21:04 UTC, frapac commented on src/prox_augmented_block.jl
> +- `P::Vector{AbstractArray}`: matrix of proximal term's penalty parameters
I am not sure to understand if `P` is an `AbstractArray` or a `Vector{AbstractArray}`?

2022-05-18 21:04 UTC, frapac commented on src/prox_augmented_block.jl
> +    A::AbstractArray # linking matrix
Maybe specify `AbstractMatrix` ?

2022-05-18 21:04 UTC, frapac commented on src/prox_augmented_block.jl
> +        name = "augmented_block",
maybe change the name to `"proximal_augmented_block"`?

2022-05-18 21:04 UTC, frapac commented on src/prox_augmented_block.jl
> +function get_hessian(
naive question: can we reuse the function we have implemented previously for `AugmentedBlockNLPModels`?

2022-05-18 21:04 UTC, frapac commented on src/prox_augmented_block.jl
> +    g .+=
I would suggest using `mul!` (to dispatch on BLAS operations) instead of the broadcast operator here

2022-05-18 21:04 UTC, frapac commented on .vscode/settings.json
> +{}
do we have to version this file?

2022-05-18 23:07 UTC, grishabh147 commented on src/prox_augmented_block.jl
> +- `P::Vector{AbstractArray}`: matrix of proximal term's penalty parameters
Sorry, this is a typo.

2022-05-19 14:26 UTC, grishabh147 commented on src/full_space.jl
> +- `x0::Union{Vector{Float64}, Nothing}`: warm start primal solution
I am already doing this through these two lines:
`isnothing(x0) && (x0 = [m.blocks[i].meta.x0 for i in 1:nb])

x0 = reduce(vcat, x0) `

2022-05-19 14:33 UTC, grishabh147 commented on src/prox_augmented_block.jl
> +    P::AbstractArray # proximal term penalty parameters
No, `P` needs to be a matrix. Isn't `AbstractMatrix <: AbstractArray`? I can make it an `AbstractMatrix` is that's more clear.

2022-05-19 15:10 UTC, frapac commented on src/full_space.jl
> +- `x0::Union{Vector{Float64}, Nothing}`: warm start primal solution
I would suggest defining these two lines directly in a function `NLPModels.get_x0`

2022-05-19 15:11 UTC, frapac commented on src/prox_augmented_block.jl
> +    P::AbstractArray # proximal term penalty parameters
You are right that `AbstractMatrix <: AbstractArray`. I would suggest typing `P::AbstractMatrix`, to force it to be a matrix.

2022-05-23 21:44 UTC, grishabh147 commented
@frapac This is now ready for a review. In addition to addressing your comments from last week, I have also tried to make changes to `augmented_block.jl` code to make the hessian computation step more efficient. Let me know if you have any comments/suggestions on my implementation.

2022-05-23 22:15 UTC, frapac approved these changes
Thanks for the update! I think this PR is ready to merge

2022-05-23 22:19 UTC, merged